// Generated by scripts/build.mjs from src/; edit the sources, not this file.
"use strict";
(() => {
  // src/shared/rules.ts
  var MAX_IMPORTS = 32;

  // src/ui/settings.ts
  var host = window.CanvasTTYPlugin;
  var SERVICE = "context";
  var GLOBAL = "";
  var STRINGS = {
    en: {
      title: "Project rules",
      lead: `Rules agents get when you launch them with "Send rules" (launcher \u2192 Advanced \u2192 Use CanvasTTY Context). Priority: the launch's own instruction \u2192 task \u2192 project \u2192 organization \u2192 user \u2192 defaults; a more specific rule with the same key wins. Claude Code gets them as an appended system prompt file, Codex as developer instructions, Grok as --rules.`,
      projects: "Projects",
      everyone: "Everyone (user and default rules)",
      addProject: "Add project",
      folder: "Folder (full path)",
      name: "Name",
      organization: "Organization (optional id)",
      remove: "Remove",
      open: "Open",
      rulesFor: (name) => `Rules \xB7 ${name}`,
      search: "Search",
      allCategories: "All categories",
      none: "No rules here yet.",
      scope: "Scope",
      task: "Task",
      category: "Category",
      key: "Key (optional, e.g. reply.language)",
      value: "Rule",
      json: "Value is JSON",
      enabled: "On",
      addRule: "Add rule",
      editRule: "Edit rule",
      saveRule: "Save rule",
      cancel: "Cancel",
      edit: "Edit",
      override: "Override",
      imported: "imported",
      off: "off",
      tokens: "Design tokens",
      conventions: "Checkable conventions (JSON presets)",
      conventionsHint: "validate.* rules use a narrow JSON vocabulary; edit the preset values before saving.",
      tasks: "Tasks",
      taskName: "Task name",
      addTask: "Add task",
      noTasks: "No tasks.",
      importTitle: "Import from project files",
      importHint: "Reads the files you select whenever rules are needed (no background scan): AGENTS.md, CLAUDE.md, GEMINI.md, CONTRIBUTING.md, .cursorrules, .windsurfrules, Cursor rules, README development sections, .editorconfig, Prettier/ESLint JSON, CSS custom properties. JavaScript configs are never run.",
      findFiles: "Find project files",
      saveImports: "Save selection",
      noFiles: "No convention files found in this folder.",
      previewTitle: "What an agent gets",
      preview: "Show",
      previewEmpty: "Nothing: no rule applies here.",
      previewSize: (size, budget, omitted) => `${size} of ${budget}${omitted ? `; ${omitted} rule(s) left out for space` : ""}`,
      saved: "Saved.",
      notSaved: "Not saved: ",
      removed: "Removed.",
      tooManyImports: (max) => `At most ${max} project files can be imported.`,
      scopes: { defaults: "Defaults", user: "You (all projects)", organization: "Organization", project: "This project", task: "Task" }
    },
    ru: {
      title: "\u041F\u0440\u0430\u0432\u0438\u043B\u0430 \u043F\u0440\u043E\u0435\u043A\u0442\u043E\u0432",
      lead: "\u041F\u0440\u0430\u0432\u0438\u043B\u0430, \u043A\u043E\u0442\u043E\u0440\u044B\u0435 \u0430\u0433\u0435\u043D\u0442\u044B \u043F\u043E\u043B\u0443\u0447\u0430\u044E\u0442 \u043F\u0440\u0438 \u0437\u0430\u043F\u0443\u0441\u043A\u0435 \u0441 \xABSend rules\xBB (\u043E\u043A\u043D\u043E \u0437\u0430\u043F\u0443\u0441\u043A\u0430 \u2192 \u0414\u043E\u043F\u043E\u043B\u043D\u0438\u0442\u0435\u043B\u044C\u043D\u043E \u2192 Use CanvasTTY Context). \u041F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442: \u0438\u043D\u0441\u0442\u0440\u0443\u043A\u0446\u0438\u044F \u0441\u0430\u043C\u043E\u0433\u043E \u0437\u0430\u043F\u0443\u0441\u043A\u0430 \u2192 \u0437\u0430\u0434\u0430\u0447\u0430 \u2192 \u043F\u0440\u043E\u0435\u043A\u0442 \u2192 \u043E\u0440\u0433\u0430\u043D\u0438\u0437\u0430\u0446\u0438\u044F \u2192 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C \u2192 \u0437\u043D\u0430\u0447\u0435\u043D\u0438\u044F \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E; \u0431\u043E\u043B\u0435\u0435 \u043A\u043E\u043D\u043A\u0440\u0435\u0442\u043D\u043E\u0435 \u043F\u0440\u0430\u0432\u0438\u043B\u043E \u0441 \u0442\u0435\u043C \u0436\u0435 \u043A\u043B\u044E\u0447\u043E\u043C \u0441\u0438\u043B\u044C\u043D\u0435\u0435. Claude Code \u043F\u043E\u043B\u0443\u0447\u0430\u0435\u0442 \u0438\u0445 \u0444\u0430\u0439\u043B\u043E\u043C, \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u043D\u044B\u043C \u043A \u0441\u0438\u0441\u0442\u0435\u043C\u043D\u043E\u043C\u0443 \u043F\u0440\u043E\u043C\u043F\u0442\u0443, Codex \u2014 \u043A\u0430\u043A developer instructions, Grok \u2014 \u0447\u0435\u0440\u0435\u0437 --rules.",
      projects: "\u041F\u0440\u043E\u0435\u043A\u0442\u044B",
      everyone: "\u0414\u043B\u044F \u0432\u0441\u0435\u0445 (\u043F\u0440\u0430\u0432\u0438\u043B\u0430 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F \u0438 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E)",
      addProject: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043F\u0440\u043E\u0435\u043A\u0442",
      folder: "\u041F\u0430\u043F\u043A\u0430 (\u043F\u043E\u043B\u043D\u044B\u0439 \u043F\u0443\u0442\u044C)",
      name: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435",
      organization: "\u041E\u0440\u0433\u0430\u043D\u0438\u0437\u0430\u0446\u0438\u044F (id, \u043D\u0435\u043E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u043E)",
      remove: "\u0423\u0434\u0430\u043B\u0438\u0442\u044C",
      open: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C",
      rulesFor: (name) => `\u041F\u0440\u0430\u0432\u0438\u043B\u0430 \xB7 ${name}`,
      search: "\u041F\u043E\u0438\u0441\u043A",
      allCategories: "\u0412\u0441\u0435 \u043A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u0438",
      none: "\u0417\u0434\u0435\u0441\u044C \u043F\u043E\u043A\u0430 \u043D\u0435\u0442 \u043F\u0440\u0430\u0432\u0438\u043B.",
      scope: "\u041E\u0431\u043B\u0430\u0441\u0442\u044C",
      task: "\u0417\u0430\u0434\u0430\u0447\u0430",
      category: "\u041A\u0430\u0442\u0435\u0433\u043E\u0440\u0438\u044F",
      key: "\u041A\u043B\u044E\u0447 (\u043D\u0435\u043E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u043E, \u043D\u0430\u043F\u0440. reply.language)",
      value: "\u041F\u0440\u0430\u0432\u0438\u043B\u043E",
      json: "\u0417\u043D\u0430\u0447\u0435\u043D\u0438\u0435 \u2014 JSON",
      enabled: "\u0412\u043A\u043B.",
      addRule: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043F\u0440\u0430\u0432\u0438\u043B\u043E",
      editRule: "\u0418\u0437\u043C\u0435\u043D\u0438\u0442\u044C \u043F\u0440\u0430\u0432\u0438\u043B\u043E",
      saveRule: "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u043F\u0440\u0430\u0432\u0438\u043B\u043E",
      cancel: "\u041E\u0442\u043C\u0435\u043D\u0430",
      edit: "\u0418\u0437\u043C\u0435\u043D\u0438\u0442\u044C",
      override: "\u041F\u0435\u0440\u0435\u043E\u043F\u0440\u0435\u0434\u0435\u043B\u0438\u0442\u044C",
      imported: "\u0438\u043C\u043F\u043E\u0440\u0442",
      off: "\u0432\u044B\u043A\u043B.",
      tokens: "\u0422\u043E\u043A\u0435\u043D\u044B \u0434\u0438\u0437\u0430\u0439\u043D\u0430",
      conventions: "\u041F\u0440\u043E\u0432\u0435\u0440\u044F\u0435\u043C\u044B\u0435 \u0441\u043E\u0433\u043B\u0430\u0448\u0435\u043D\u0438\u044F (\u0448\u0430\u0431\u043B\u043E\u043D\u044B JSON)",
      conventionsHint: "\u041A\u043B\u044E\u0447\u0438 validate.* \u0438\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u044E\u0442 \u0443\u0437\u043A\u0438\u0439 \u0444\u043E\u0440\u043C\u0430\u0442 JSON; \u043E\u0442\u0440\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u0443\u0439\u0442\u0435 \u0437\u043D\u0430\u0447\u0435\u043D\u0438\u044F \u0448\u0430\u0431\u043B\u043E\u043D\u0430 \u043F\u0435\u0440\u0435\u0434 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u0435\u043C.",
      tasks: "\u0417\u0430\u0434\u0430\u0447\u0438",
      taskName: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u0437\u0430\u0434\u0430\u0447\u0438",
      addTask: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0437\u0430\u0434\u0430\u0447\u0443",
      noTasks: "\u0417\u0430\u0434\u0430\u0447 \u043D\u0435\u0442.",
      importTitle: "\u0418\u043C\u043F\u043E\u0440\u0442 \u0438\u0437 \u0444\u0430\u0439\u043B\u043E\u0432 \u043F\u0440\u043E\u0435\u043A\u0442\u0430",
      importHint: "\u0412\u044B\u0431\u0440\u0430\u043D\u043D\u044B\u0435 \u0444\u0430\u0439\u043B\u044B \u0447\u0438\u0442\u0430\u044E\u0442\u0441\u044F \u043A\u0430\u0436\u0434\u044B\u0439 \u0440\u0430\u0437, \u043A\u043E\u0433\u0434\u0430 \u043D\u0443\u0436\u043D\u044B \u043F\u0440\u0430\u0432\u0438\u043B\u0430 (\u0431\u0435\u0437 \u0444\u043E\u043D\u043E\u0432\u043E\u0433\u043E \u0441\u043A\u0430\u043D\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F): AGENTS.md, CLAUDE.md, GEMINI.md, CONTRIBUTING.md, .cursorrules, .windsurfrules, \u043F\u0440\u0430\u0432\u0438\u043B\u0430 Cursor, \u0440\u0430\u0437\u0434\u0435\u043B\u044B README \u043E \u0440\u0430\u0437\u0440\u0430\u0431\u043E\u0442\u043A\u0435, .editorconfig, JSON Prettier/ESLint, CSS-\u043F\u0435\u0440\u0435\u043C\u0435\u043D\u043D\u044B\u0435. JavaScript-\u043A\u043E\u043D\u0444\u0438\u0433\u0438 \u043D\u0435 \u0437\u0430\u043F\u0443\u0441\u043A\u0430\u044E\u0442\u0441\u044F.",
      findFiles: "\u041D\u0430\u0439\u0442\u0438 \u0444\u0430\u0439\u043B\u044B \u043F\u0440\u043E\u0435\u043A\u0442\u0430",
      saveImports: "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C \u0432\u044B\u0431\u043E\u0440",
      noFiles: "\u0412 \u044D\u0442\u043E\u0439 \u043F\u0430\u043F\u043A\u0435 \u043D\u0435\u0442 \u0444\u0430\u0439\u043B\u043E\u0432 \u0441 \u0441\u043E\u0433\u043B\u0430\u0448\u0435\u043D\u0438\u044F\u043C\u0438.",
      previewTitle: "\u0427\u0442\u043E \u043F\u043E\u043B\u0443\u0447\u0438\u0442 \u0430\u0433\u0435\u043D\u0442",
      preview: "\u041F\u043E\u043A\u0430\u0437\u0430\u0442\u044C",
      previewEmpty: "\u041D\u0438\u0447\u0435\u0433\u043E: \u0437\u0434\u0435\u0441\u044C \u043D\u0435 \u0434\u0435\u0439\u0441\u0442\u0432\u0443\u0435\u0442 \u043D\u0438 \u043E\u0434\u043D\u043E \u043F\u0440\u0430\u0432\u0438\u043B\u043E.",
      previewSize: (size, budget, omitted) => `${size} \u0438\u0437 ${budget}${omitted ? `; \u043D\u0435 \u043F\u043E\u043C\u0435\u0441\u0442\u0438\u043B\u043E\u0441\u044C \u043F\u0440\u0430\u0432\u0438\u043B: ${omitted}` : ""}`,
      saved: "\u0421\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u043E.",
      notSaved: "\u041D\u0435 \u0441\u043E\u0445\u0440\u0430\u043D\u0435\u043D\u043E: ",
      removed: "\u0423\u0434\u0430\u043B\u0435\u043D\u043E.",
      tooManyImports: (max) => `\u0418\u043C\u043F\u043E\u0440\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043C\u043E\u0436\u043D\u043E \u043D\u0435 \u0431\u043E\u043B\u044C\u0448\u0435 ${max} \u0444\u0430\u0439\u043B\u043E\u0432 \u043F\u0440\u043E\u0435\u043A\u0442\u0430.`,
      scopes: { defaults: "\u041F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E", user: "\u0412\u044B (\u0432\u0441\u0435 \u043F\u0440\u043E\u0435\u043A\u0442\u044B)", organization: "\u041E\u0440\u0433\u0430\u043D\u0438\u0437\u0430\u0446\u0438\u044F", project: "\u042D\u0442\u043E\u0442 \u043F\u0440\u043E\u0435\u043A\u0442", task: "\u0417\u0430\u0434\u0430\u0447\u0430" }
    }
  };
  var CATEGORY_RU = {
    design: "\u0434\u0438\u0437\u0430\u0439\u043D",
    architecture: "\u0430\u0440\u0445\u0438\u0442\u0435\u043A\u0442\u0443\u0440\u0430",
    "code-style": "\u0441\u0442\u0438\u043B\u044C \u043A\u043E\u0434\u0430",
    security: "\u0431\u0435\u0437\u043E\u043F\u0430\u0441\u043D\u043E\u0441\u0442\u044C",
    testing: "\u0442\u0435\u0441\u0442\u044B",
    deployment: "\u0440\u0430\u0437\u0432\u0451\u0440\u0442\u044B\u0432\u0430\u043D\u0438\u0435",
    documentation: "\u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430\u0446\u0438\u044F",
    "business-rules": "\u0431\u0438\u0437\u043D\u0435\u0441-\u043F\u0440\u0430\u0432\u0438\u043B\u0430",
    naming: "\u0438\u043C\u0435\u043D\u0430",
    dependencies: "\u0437\u0430\u0432\u0438\u0441\u0438\u043C\u043E\u0441\u0442\u0438",
    communication: "\u043E\u0431\u0449\u0435\u043D\u0438\u0435"
  };
  var locale = "en";
  var t = STRINGS.en;
  var data = null;
  var selected = GLOBAL;
  var search = "";
  var filter = "";
  var draft = null;
  var importedRules = [];
  var importNotes = [];
  var importError = "";
  var candidates = null;
  var candidatesFor = "";
  var view = 0;
  var preview = null;
  var previewCli = "claude";
  var root = document.querySelector("#app");
  var status = document.querySelector("#status");
  var say = (message) => {
    status.textContent = message;
  };
  var errorText = (error) => error instanceof Error ? error.message : String(error);
  var request = (method, params) => host.service.request(SERVICE, method, params);
  var categoryLabel = (category) => locale === "ru" ? CATEGORY_RU[category] ?? category : category;
  function el(tag, props = {}, ...children) {
    const node = document.createElement(tag);
    const { dataset, ...rest } = props;
    Object.assign(node, rest);
    if (dataset) Object.assign(node.dataset, dataset);
    node.append(...children);
    return node;
  }
  var button = (label, name, onClick) => {
    const node = el("button", { type: "button", textContent: label, name });
    node.addEventListener("click", onClick);
    return node;
  };
  var field = (label, control) => el("label", { className: "field" }, el("span", { textContent: label }), control);
  var select = (name, options, value, onChange) => {
    const node = el("select", { name });
    for (const [optionValue, label] of options) node.append(el("option", { value: optionValue, textContent: label }));
    node.value = value;
    if (onChange) node.addEventListener("change", () => onChange(node.value));
    return node;
  };
  var project = () => data?.state.projects.find((p) => p.id === selected);
  var projectTasks = () => data?.state.tasks.filter((task) => task.projectId === selected) ?? [];
  async function load() {
    data = await request("state");
    if (selected && !project()) {
      selected = GLOBAL;
      view++;
      candidates = null;
      preview = null;
    }
    await loadImported();
    render();
  }
  async function loadImported() {
    importedRules = [];
    importNotes = [];
    importError = "";
    if (!selected) return;
    const asked = { projectId: selected, view };
    const answer = await request("imported", { projectId: asked.projectId });
    if (asked.view !== view || asked.projectId !== selected) return;
    if ("error" in answer) importError = answer.error;
    else {
      importedRules = answer.rules;
      importNotes = answer.diagnostics;
    }
  }
  function choose(id) {
    selected = id;
    view++;
    draft = null;
    candidates = null;
    preview = null;
    void loadImported().then(render);
  }
  async function change(method, params, done = t.saved) {
    if (!data) return null;
    try {
      const next = await request(method, { ...params, revision: data.state.revision });
      say(done);
      await load();
      return next;
    } catch (error) {
      say(`${t.notSaved}${errorText(error)}`);
      return null;
    }
  }
  function visibleRules() {
    if (!data) return [];
    const p = project();
    const tasks = new Set(projectTasks().map((task) => task.id));
    const own = data.state.rules.filter((rule) => rule.scope === "defaults" || rule.scope === "user" || p && (rule.scope === "project" && rule.ownerId === p.id || rule.scope === "organization" && rule.ownerId === p.organizationId || rule.scope === "task" && tasks.has(rule.ownerId)));
    const needle = search.trim().toLocaleLowerCase();
    return [...own, ...importedRules].filter((rule) => (!filter || rule.category === filter) && (!needle || `${rule.key} ${typeof rule.value === "string" ? rule.value : JSON.stringify(rule.value)}`.toLocaleLowerCase().includes(needle)));
  }
  var valueText = (value) => typeof value === "string" ? value : JSON.stringify(value, null, 2);
  var slug = (text) => text.toLowerCase().normalize("NFKD").replace(/[^a-z0-9а-яё]+/giu, "-").replace(/^-+|-+$/gu, "").slice(0, 40) || "rule";
  function ruleItem(rule) {
    const item = el("li", { className: `rule${rule.enabled ? "" : " rule--off"}`, dataset: { rule: rule.id, key: rule.key } });
    const task = rule.scope === "task" ? data.state.tasks.find((entry) => entry.id === rule.ownerId)?.label : void 0;
    const where = `${t.scopes[rule.scope] ?? rule.scope}${task ? `: ${task}` : ""}`;
    const origin = rule.source === "imported" && rule.provenance ? ` \xB7 ${t.imported} ${rule.provenance.sourcePath}:${rule.provenance.sourceLine}` : "";
    item.append(
      el("div", { className: "rule__head" }, el("strong", { textContent: rule.key }), el("span", { className: "muted", textContent: ` ${where} \xB7 ${categoryLabel(rule.category)}${origin}${rule.enabled ? "" : ` \xB7 ${t.off}`}` })),
      el("pre", { className: "rule__value", textContent: valueText(rule.value).slice(0, 600) })
    );
    const actions = el("div", { className: "row" });
    if (rule.source === "imported") {
      actions.append(button(t.override, `override-${rule.id}`, () => {
        draft = { scope: "project", category: rule.category, key: rule.key, valueText: valueText(rule.value), json: typeof rule.value !== "string", enabled: true };
        render();
      }));
    } else {
      actions.append(
        button(t.edit, `edit-${rule.id}`, () => {
          draft = {
            id: rule.id,
            scope: rule.scope,
            ...rule.scope === "task" ? { taskId: rule.ownerId } : {},
            category: rule.category,
            key: rule.key,
            valueText: valueText(rule.value),
            json: typeof rule.value !== "string",
            enabled: rule.enabled
          };
          render();
        }),
        button(t.remove, `remove-${rule.id}`, () => void change("remove", { kind: "rule", id: rule.id }, t.removed))
      );
    }
    item.append(actions);
    return item;
  }
  function scopeOptions() {
    const p = project();
    const options = [];
    if (p) options.push(["project", t.scopes.project]);
    if (p && projectTasks().length) options.push(["task", t.scopes.task]);
    if (p?.organizationId) options.push(["organization", `${t.scopes.organization} ${p.organizationId}`]);
    options.push(["user", t.scopes.user], ["defaults", t.scopes.defaults]);
    return options;
  }
  function ruleForm() {
    const p = project();
    const current = draft ?? { scope: p ? "project" : "user", category: "communication", key: "", valueText: "", json: false, enabled: true };
    const box = el("div", { className: "rule-form" });
    const scope = select("rule-scope", scopeOptions(), current.scope);
    const tasks = projectTasks();
    const task = select("rule-task", tasks.map((entry) => [entry.id, entry.label]), current.taskId ?? tasks[0]?.id ?? "");
    const taskField = field(t.task, task);
    taskField.hidden = scope.value !== "task";
    scope.addEventListener("change", () => {
      taskField.hidden = scope.value !== "task";
    });
    const category = select("rule-category", data.categories.map((entry) => [entry, categoryLabel(entry)]), current.category);
    const key = el("input", { name: "rule-key", value: current.key, placeholder: "reply.language", maxLength: 160 });
    const value = el("textarea", { name: "rule-value", value: current.valueText, rows: 4 });
    const json = el("input", { type: "checkbox", name: "rule-json", checked: current.json });
    const enabled = el("input", { type: "checkbox", name: "rule-enabled", checked: current.enabled });
    const usePreset = (preset) => {
      draft = { ...draft?.id ? { id: draft.id } : {}, scope: p ? "project" : "user", category: preset.category, key: preset.key, valueText: valueText(preset.value), json: typeof preset.value !== "string", enabled: true };
      render();
    };
    box.append(
      el("h3", { textContent: current.id ? t.editRule : t.addRule }),
      el("div", { className: "row" }, field(t.scope, scope), taskField, field(t.category, category), field(t.key, key)),
      field(t.value, value),
      el("div", { className: "row" }, el("label", { className: "check" }, json, ` ${t.json}`), el("label", { className: "check" }, enabled, ` ${t.enabled}`)),
      el(
        "div",
        { className: "row" },
        button(t.saveRule, "save-rule", () => {
          let parsed = value.value;
          if (json.checked) {
            try {
              parsed = JSON.parse(value.value);
            } catch (error) {
              say(`${t.notSaved}${errorText(error)}`);
              return;
            }
          }
          const chosenScope = scope.value;
          const ownerId = chosenScope === "project" ? p?.id : chosenScope === "organization" ? p?.organizationId : chosenScope === "task" ? task.value : void 0;
          const ruleKey = key.value.trim() || `rule.${slug(typeof parsed === "string" ? parsed.split(/\s+/u).slice(0, 5).join(" ") : category.value)}`;
          void change("saveRule", { rule: { ...current.id ? { id: current.id } : {}, scope: chosenScope, ...ownerId ? { ownerId } : {}, category: category.value, key: ruleKey, value: parsed, enabled: enabled.checked } }).then((ok) => {
            if (ok) {
              draft = null;
              render();
            }
          });
        }),
        button(t.cancel, "cancel-rule", () => {
          draft = null;
          render();
        })
      ),
      el("details", {}, el("summary", { textContent: t.tokens }), el("div", { className: "row" }, ...data.presets.tokens.map((preset) => button(locale === "ru" ? preset.ru : preset.en, `preset-${preset.id}`, () => usePreset(preset))))),
      el(
        "details",
        {},
        el("summary", { textContent: t.conventions }),
        el("p", { className: "muted", textContent: t.conventionsHint }),
        el("div", { className: "row" }, ...data.presets.conventions.map((preset) => button(locale === "ru" ? preset.ru : preset.en, `preset-${preset.id}`, () => usePreset(preset))))
      )
    );
    return box;
  }
  function projectsSection() {
    const list = el("ul", { className: "projects" });
    const entry = (id, label, detail, removable) => {
      const item = el("li", { className: `project${selected === id ? " project--selected" : ""}`, dataset: { project: id || "global" } });
      item.append(
        button(label, `open-${id || "global"}`, () => choose(id)),
        el("span", { className: "muted", textContent: detail })
      );
      if (removable) item.append(button(t.remove, `remove-project-${id}`, () => void change("remove", { kind: "project", id }, t.removed)));
      return item;
    };
    list.append(entry(GLOBAL, t.everyone, "", false));
    for (const p of data.state.projects) list.append(entry(p.id, p.label, ` ${p.root}${p.organizationId ? ` \xB7 ${p.organizationId}` : ""}`, true));
    const folder = el("input", { name: "project-root", placeholder: "/Users/you/project" });
    const name = el("input", { name: "project-label" });
    const organization = el("input", { name: "project-org" });
    return el(
      "section",
      {},
      el("h2", { textContent: t.projects }),
      list,
      el(
        "div",
        { className: "row add" },
        field(t.folder, folder),
        field(t.name, name),
        field(t.organization, organization),
        button(t.addProject, "add-project", () => {
          const root2 = folder.value.trim();
          const label = name.value.trim() || root2.split("/").filter(Boolean).pop() || root2;
          const before = new Set(data?.state.projects.map((p) => p.id));
          void change("saveProject", { project: { label, root: root2, ...organization.value.trim() ? { organizationId: organization.value.trim() } : {} } }).then((next) => {
            const added = next?.projects.find((p) => !before.has(p.id));
            if (added && data?.state.projects.some((p) => p.id === added.id)) {
              choose(added.id);
              render();
            }
          });
        })
      )
    );
  }
  function tasksSection() {
    const list = el("ul", { className: "tasks" });
    const tasks = projectTasks();
    if (!tasks.length) list.append(el("li", { className: "muted", textContent: t.noTasks }));
    for (const task of tasks) list.append(el("li", { dataset: { task: task.id } }, `${task.label} `, button(t.remove, `remove-task-${task.id}`, () => void change("remove", { kind: "task", id: task.id }, t.removed))));
    const label = el("input", { name: "task-label" });
    return el(
      "section",
      {},
      el("h3", { textContent: t.tasks }),
      list,
      el("div", { className: "row" }, field(t.taskName, label), button(t.addTask, "add-task", () => {
        if (label.value.trim()) void change("saveTask", { task: { label: label.value.trim(), projectId: selected } });
      }))
    );
  }
  function importSection() {
    const box = el(
      "section",
      { className: "imports" },
      el("h3", { textContent: t.importTitle }),
      el("p", { className: "muted", textContent: t.importHint }),
      button(t.findFiles, "find-files", () => {
        const asked = { projectId: selected, view };
        request("discover", { projectId: asked.projectId }).then((found) => {
          if (asked.view !== view) return;
          candidates = found;
          candidatesFor = asked.projectId;
          render();
        }, (error) => say(errorText(error)));
      })
    );
    if (candidates) {
      if (!candidates.length) box.append(el("p", { className: "muted", textContent: t.noFiles }));
      const boxes = candidates.map((candidate) => {
        const input = el("input", { type: "checkbox", checked: candidate.selected, name: `import-${candidate.path}` });
        input.addEventListener("change", () => {
          if (input.checked && boxes.filter((entry) => entry.input.checked).length > MAX_IMPORTS) {
            input.checked = false;
            say(t.tooManyImports(MAX_IMPORTS));
          }
        });
        box.append(el("label", { className: "check file" }, input, ` ${candidate.path} `, el("span", { className: "muted", textContent: candidate.kind })));
        return { candidate, input };
      });
      if (candidates.length) {
        box.append(el("div", { className: "row" }, button(t.saveImports, "save-imports", () => {
          const imports = boxes.filter((entry) => entry.input.checked).map((entry) => ({ path: entry.candidate.path, kind: entry.candidate.kind }));
          if (imports.length > MAX_IMPORTS) {
            say(t.tooManyImports(MAX_IMPORTS));
            return;
          }
          void change("saveImports", { projectId: candidatesFor, imports }).then((next) => {
            if (next) {
              candidates = null;
              render();
            }
          });
        })));
      }
    }
    if (importError) box.append(el("p", { className: "error", textContent: importError }));
    for (const note of importNotes) box.append(el("p", { className: "muted", textContent: `${note.sourcePath}: ${note.message}` }));
    return box;
  }
  function previewSection() {
    const cli = select("preview-cli", [["claude", "Claude Code"], ["codex", "Codex"], ["grok", "Grok"]], previewCli, (value) => {
      previewCli = value;
    });
    const box = el("section", {}, el("h3", { textContent: t.previewTitle }), el("div", { className: "row" }, cli, button(t.preview, "preview", () => {
      const asked = view;
      request("preview", { provider: previewCli, ...selected ? { projectId: selected } : {} }).then((answer) => {
        if (asked !== view) return;
        preview = answer;
        render();
      }, (error) => say(errorText(error)));
    })));
    if (preview) {
      box.append(
        el("p", { className: "muted", textContent: t.previewSize(preview.size, preview.budget, preview.omitted) }),
        el("pre", { className: "preview", textContent: preview.text || t.previewEmpty })
      );
    }
    return box;
  }
  function rulesList() {
    const rules = visibleRules();
    const list = el("ul", { className: "rules" });
    if (!rules.length) list.append(el("li", { className: "muted", textContent: t.none }));
    for (const rule of rules) list.append(ruleItem(rule));
    return list;
  }
  function render() {
    if (!data) return;
    const p = project();
    const slot = el("div", {}, rulesList());
    const searchInput = el("input", { name: "search", value: search, placeholder: t.search, type: "search" });
    searchInput.addEventListener("input", () => {
      search = searchInput.value;
      slot.replaceChildren(rulesList());
    });
    const categories = select("filter-category", [["", t.allCategories], ...data.categories.map((entry) => [entry, categoryLabel(entry)])], filter, (value) => {
      filter = value;
      slot.replaceChildren(rulesList());
    });
    root.replaceChildren(
      el("h1", { textContent: t.title }),
      el("p", { className: "muted", textContent: t.lead }),
      projectsSection(),
      el("section", {}, el("h2", { textContent: t.rulesFor(p?.label ?? t.everyone) }), el("div", { className: "row" }, searchInput, categories), slot),
      ruleForm(),
      ...p ? [tasksSection(), importSection()] : [],
      previewSection()
    );
  }
  host.onContext(({ appearance }) => {
    locale = appearance.locale === "ru" ? "ru" : "en";
    t = STRINGS[locale];
    document.documentElement.lang = locale;
    render();
  });
  load().catch((error) => say(errorText(error)));
})();
