// Generated by scripts/build.mjs from src/; edit the sources, not this file.

// src/rpc.ts
var RPC_LIMITS = Object.freeze({
  /** CanvasTTY caps service frames at 1 MiB in both directions. */
  frameBytes: 1048576,
  hostCallMs: 3e4,
  hostCalls: 64,
  activeHandlers: 64,
  /** CanvasTTY waits 2 s after canvastty.shutdown before SIGTERM. */
  drainMs: 1500
});
function serve({ methods, notifications = {}, onInitialize, input = process.stdin, output = process.stdout, exit = (code) => process.exit(code), limits = {} }) {
  const limit = { ...RPC_LIMITS, ...limits };
  const pending = /* @__PURE__ */ new Map();
  let nextId = 1;
  let active = 0;
  let stopping = false;
  let hostGone = false;
  let onIdle = null;
  const send = (message) => {
    output.write(`${JSON.stringify({ jsonrpc: "2.0", ...message })}
`);
  };
  const host = {
    callHost: (method, params) => new Promise((resolve, reject) => {
      if (hostGone) {
        reject(new Error("The host connection is closed."));
        return;
      }
      if (pending.size >= limit.hostCalls) {
        reject(new Error("Too many host calls in flight."));
        return;
      }
      const id = nextId++;
      const timer = setTimeout(() => {
        pending.delete(id);
        reject(new Error(`The host did not answer ${method} in time.`));
      }, limit.hostCallMs);
      pending.set(id, { resolve, reject, timer });
      send({ id, method, params });
    }),
    log: (level, message) => send({ method: "log", params: { level, message: String(message).slice(0, 500) } }),
    emit: (event, data) => send({ method: "event", params: { event, data } })
  };
  const record = (value) => value && typeof value === "object" && !Array.isArray(value) ? value : {};
  const errorText2 = (error) => error instanceof Error ? error.message : String(error);
  const track = (run) => {
    active++;
    return Promise.resolve().then(run).finally(() => {
      active--;
      if (active === 0) onIdle?.();
    });
  };
  const stop = () => {
    if (stopping) return;
    stopping = true;
    const timer = setTimeout(() => exit(0), limit.drainMs);
    onIdle = () => {
      clearTimeout(timer);
      exit(0);
    };
    if (active === 0) onIdle();
  };
  const handle = (line) => {
    let message;
    try {
      message = record(JSON.parse(line));
    } catch {
      return;
    }
    const method = message.method;
    if (method === "canvastty.initialize") {
      Promise.resolve().then(() => onInitialize?.(record(message.params), host)).catch((error2) => host.log("error", `initialize failed: ${errorText2(error2)}`));
      return;
    }
    if (method === "canvastty.shutdown") {
      stop();
      return;
    }
    if (typeof method === "string" && message.id === void 0) {
      if (stopping) return;
      if (active >= limit.activeHandlers) {
        host.log("warn", `${method}: dropped, the service is busy`);
        return;
      }
      const handler = Object.hasOwn(notifications, method) ? notifications[method] : void 0;
      track(() => handler?.(record(message.params), host)).catch((error2) => host.log("warn", `${method}: ${errorText2(error2)}`));
      return;
    }
    if (typeof method === "string") {
      if (stopping || active >= limit.activeHandlers) {
        send({ id: message.id, error: { code: -32e3, message: stopping ? "The service is stopping." : "The service is busy; try again." } });
        return;
      }
      const handler = Object.hasOwn(methods, method) ? methods[method] : void 0;
      track(() => {
        if (!handler) throw Object.assign(new Error(`Unknown method: ${method}`), { code: -32601 });
        return handler(record(message.params), host);
      }).then(
        (result) => send({ id: message.id, result: result ?? null }),
        (error2) => send({ id: message.id, error: { code: error2?.code ?? -32e3, message: errorText2(error2).slice(0, 400) } })
      );
      return;
    }
    const waiter = typeof message.id === "number" ? pending.get(message.id) : void 0;
    if (!waiter) return;
    pending.delete(message.id);
    clearTimeout(waiter.timer);
    const error = record(message.error);
    if (message.error) waiter.reject(new Error(typeof error.message === "string" ? error.message : "Host request failed."));
    else waiter.resolve(message.result);
  };
  let chunks = [];
  let size = 0;
  let skipping = false;
  const drop = () => {
    if (!skipping) host.log("warn", "Dropped a host message larger than the frame limit.");
    chunks = [];
    size = 0;
  };
  input.on("data", (data) => {
    let chunk = typeof data === "string" ? Buffer.from(data) : data;
    for (let newline = chunk.indexOf(10); newline >= 0; newline = chunk.indexOf(10)) {
      const part = chunk.subarray(0, newline);
      chunk = chunk.subarray(newline + 1);
      if (skipping || size + part.length > limit.frameBytes) {
        drop();
        skipping = false;
        continue;
      }
      const line = (chunks.length ? Buffer.concat([...chunks, part]) : part).toString("utf8");
      chunks = [];
      size = 0;
      handle(line);
    }
    if (!chunk.length || skipping) return;
    if (size + chunk.length > limit.frameBytes) {
      drop();
      skipping = true;
      return;
    }
    chunks.push(Buffer.from(chunk));
    size += chunk.length;
  });
  const closed = () => {
    if (hostGone) return;
    hostGone = true;
    for (const waiter of pending.values()) {
      clearTimeout(waiter.timer);
      waiter.reject(new Error("The host connection closed."));
    }
    pending.clear();
    stop();
  };
  input.on("end", closed);
  input.on("error", closed);
}

// src/shared/rules.ts
var CATEGORIES = ["design", "architecture", "code-style", "security", "testing", "deployment", "documentation", "business-rules", "naming", "dependencies", "communication"];
var SCOPES = ["defaults", "user", "organization", "project", "task", "current"];
var MAX_RULES = 2e3;
var MAX_IMPORTS = 32;
var dangerous = /* @__PURE__ */ new Set(["__proto__", "prototype", "constructor"]);
var sources = ["imported", "explicit"];
var bytes = (value) => new TextEncoder().encode(value).length;
var emptyState = () => ({ version: 1, revision: 0, projects: [], tasks: [], rules: [] });
function checkText(value, limit, name, empty = false) {
  if (typeof value !== "string" || !empty && !value.trim() || bytes(value) > limit || /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/u.test(value)) throw new Error(`Invalid or too long ${name}.`);
}
function checkKey(value) {
  checkText(value, 160, "rule key");
  if (/[\t\n\r\u2028\u2029]/u.test(value)) throw new Error("Invalid or too long rule key.");
}
function checkId(value, name = "id") {
  if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u.test(value)) throw new Error(`Invalid ${name}: letters, digits, dot, dash or underscore, up to 64.`);
}
function importNameSupported(kind, path) {
  const parts = path.split("/");
  const name = parts.at(-1);
  switch (kind) {
    case "instructions":
      return /^(?:AGENTS|CLAUDE|CONTRIBUTING|GEMINI)\.md$/iu.test(name) || name === ".cursorrules" || name === ".windsurfrules" || path === ".github/copilot-instructions.md" || parts.includes(".cursor") && parts.includes("rules") && name.endsWith(".mdc");
    case "readme":
      return /^README(?:\.md)?$/iu.test(name);
    case "editorconfig":
      return name === ".editorconfig";
    case "css":
      return name.endsWith(".css");
    case "config":
      return /^(?:\.?prettier(?:rc|\.config)|\.?eslint(?:rc|\.config))(?:\.(?:json|ya?ml|[cm]?js|ts))?$/u.test(name);
  }
}
function checkImports(imports) {
  if (!Array.isArray(imports) || imports.length > MAX_IMPORTS) throw new Error(`At most ${MAX_IMPORTS} project files can be imported.`);
  const paths = /* @__PURE__ */ new Set();
  for (const entry of imports) {
    if (!entry || typeof entry !== "object" || Object.keys(entry).some((key) => !["path", "kind", "selectors"].includes(key))) throw new Error("Invalid import entry.");
    checkText(entry.path, 1024, "import path");
    const parts = entry.path.split("/");
    if (paths.has(entry.path) || parts.length > 20 || parts.some((part) => !part || part === "." || part === ".." || part === ".git" || part === "node_modules" || bytes(part) > 255) || /[\\:\x00-\x1f\x7f]/u.test(entry.path) || /[\uD800-\uDFFF]/u.test(entry.path)) throw new Error(`Import path ${entry.path.slice(0, 80)} is not a plain path inside the project.`);
    paths.add(entry.path);
    if (!["instructions", "readme", "editorconfig", "config", "css"].includes(entry.kind)) throw new Error("Invalid import kind.");
    if (!importNameSupported(entry.kind, entry.path)) throw new Error(`${entry.path.slice(0, 80)} is not a file this import reads.`);
    if (entry.selectors !== void 0 && (entry.kind !== "css" || !Array.isArray(entry.selectors) || !entry.selectors.length || entry.selectors.length > 8 || entry.selectors.some((s) => typeof s !== "string" || bytes(s) > 120 || !/^(?::root|\.[A-Za-z_][A-Za-z0-9_-]*|\[data-theme=["']?[A-Za-z0-9_-]+["']?\])$/u.test(s)))) throw new Error("Invalid CSS theme selector.");
  }
}
function checkValue(value, depth = 0) {
  if (depth > 4) throw new Error("A rule value is nested too deeply.");
  if (value === null || typeof value === "boolean") return;
  if (typeof value === "number" && Number.isFinite(value)) return;
  if (typeof value === "string") {
    checkText(value, 4096, "rule text", true);
    return;
  }
  if (!value || typeof value !== "object" || Object.keys(value).length > 64) throw new Error("Invalid rule value.");
  for (const [key, child] of Object.entries(value)) {
    if (dangerous.has(key)) throw new Error("Unsafe key in a rule value.");
    checkText(key, 160, "value key");
    checkValue(child, depth + 1);
  }
}
function checkRule(value) {
  const rule = value;
  if (!rule || typeof rule !== "object" || Array.isArray(rule)) throw new Error("Invalid rule.");
  checkId(rule.id, "rule id");
  checkText(rule.key, 160, "rule key");
  if (dangerous.has(rule.key) || !SCOPES.includes(rule.scope) || !CATEGORIES.includes(rule.category) || !sources.includes(rule.source) || typeof rule.enabled !== "boolean" || !Number.isSafeInteger(rule.updatedAt) || rule.updatedAt < 0) throw new Error("Invalid rule fields.");
  if (rule.scope === "project" || rule.scope === "organization" || rule.scope === "task") checkId(rule.ownerId, `${rule.scope} of the rule`);
  else if (rule.ownerId !== void 0) throw new Error("This scope has no owner.");
  checkValue(rule.value);
  if (rule.provenance !== void 0) {
    const p = rule.provenance;
    if (rule.source !== "imported" || !p || Object.keys(p).some((k) => !["sourcePath", "sourceLine"].includes(k)) || !Number.isSafeInteger(p.sourceLine) || p.sourceLine < 1) throw new Error("Invalid imported rule origin.");
    checkText(p.sourcePath, 1024, "import path");
  }
  if (bytes(JSON.stringify(rule)) > 4096) throw new Error("The rule is longer than 4 KB.");
}
function checkState(value) {
  const s = value;
  if (!s || s.version !== 1 || !Number.isSafeInteger(s.revision) || s.revision < 0 || !Array.isArray(s.projects) || s.projects.length > 128 || !Array.isArray(s.tasks) || s.tasks.length > 256 || !Array.isArray(s.rules) || s.rules.length > MAX_RULES) throw new Error("Invalid or too large rules store.");
  const projects = /* @__PURE__ */ new Set(), organizations = /* @__PURE__ */ new Set(), tasks = /* @__PURE__ */ new Set(), rules = /* @__PURE__ */ new Set();
  for (const p of s.projects) {
    checkId(p.id, "project id");
    checkText(p.label, 160, "project name");
    checkText(p.root, 4096, "project folder");
    if (typeof p.rootIdentity !== "string" || !/^\d+:\d+:\d+$/u.test(p.rootIdentity)) throw new Error("Invalid project folder identity.");
    if (p.imports !== void 0) checkImports(p.imports);
    if (projects.has(p.id)) throw new Error("Duplicate project.");
    projects.add(p.id);
    if (p.organizationId !== void 0) {
      checkId(p.organizationId, "organization");
      organizations.add(p.organizationId);
    }
  }
  for (const t of s.tasks) {
    checkId(t.id, "task id");
    checkText(t.label, 160, "task name");
    if (!projects.has(t.projectId) || tasks.has(t.id)) throw new Error("A task needs its project.");
    tasks.add(t.id);
  }
  for (const r of s.rules) {
    checkRule(r);
    if (r.source !== "explicit" || rules.has(r.id) || r.scope === "current" || r.scope === "project" && !projects.has(r.ownerId) || r.scope === "task" && !tasks.has(r.ownerId) || r.scope === "organization" && !organizations.has(r.ownerId)) throw new Error("A stored rule has an unknown scope owner.");
    rules.add(r.id);
  }
}
var HEADING = "CanvasTTY project rules, set by the person. Follow them; the person's current instructions take precedence.\n";
var DEFAULT_BUDGET = 12288;
var SCOPE_SHARE = { defaults: 1024, user: 2048, organization: 2048, project: 6144, task: 4096, current: 4096 };
var mandatory = (rule) => rule.category === "security" || rule.category === "dependencies" || rule.scope === "current";
var priority = (rule) => SCOPES.indexOf(rule.scope) * 10 + sources.indexOf(rule.source);
function ruleLine(rule) {
  const value = typeof rule.value === "string" ? rule.value.trim() : JSON.stringify(rule.value);
  return `- [${rule.category}] ${rule.key.replace(/\s+/gu, " ")}: ${value.replace(/\r?\n/gu, "\n  ")}
`;
}
function resolveRules(rules, selection) {
  if (rules.length > MAX_RULES + 64) throw new Error("Too many rules to resolve.");
  const winners = /* @__PURE__ */ new Map();
  for (const rule of rules) {
    checkRule(rule);
    if (!rule.enabled || rule.scope === "project" && rule.ownerId !== selection.projectId || rule.scope === "organization" && rule.ownerId !== selection.organizationId || rule.scope === "task" && rule.ownerId !== selection.taskId) continue;
    const previous = winners.get(rule.key);
    if (!previous || priority(rule) > priority(previous) || priority(rule) === priority(previous) && (rule.updatedAt > previous.updatedAt || rule.updatedAt === previous.updatedAt && rule.id.localeCompare(previous.id) > 0)) winners.set(rule.key, rule);
  }
  const visible = [...winners.values()].filter((rule) => !selection.categories?.length || mandatory(rule) || selection.categories.includes(rule.category));
  visible.sort((a, b) => Number(mandatory(b)) - Number(mandatory(a)) || priority(b) - priority(a) || a.key.localeCompare(b.key, "en", { numeric: true }));
  const budget = selection.budget ?? DEFAULT_BUDGET;
  const measure = selection.measure ?? bytes;
  const scale = budget / DEFAULT_BUDGET;
  const used = /* @__PURE__ */ new Map();
  const included = [];
  let text = "", omitted = 0;
  for (const rule of visible) {
    const line = ruleLine(rule), size = bytes(line);
    const candidate = (text || HEADING) + line;
    if (measure(candidate) > budget || !mandatory(rule) && (used.get(rule.scope) ?? 0) + size > SCOPE_SHARE[rule.scope] * scale) {
      if (mandatory(rule)) throw new Error(`The rules do not fit what this agent accepts at launch (security, dependencies and the launch instruction are never left out): ${rule.key.slice(0, 60)}. Shorten them or turn off Send rules.`);
      omitted++;
      continue;
    }
    text = candidate;
    included.push(structuredClone(rule));
    used.set(rule.scope, (used.get(rule.scope) ?? 0) + size);
  }
  return { text, included, omitted, size: text ? measure(text) : 0 };
}

// src/shared/presets.ts
var color = (v) => typeof v === "string" && /^#[0-9a-f]{6}(?:[0-9a-f]{2})?$/iu.test(v);
function parseConventionRule(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return;
  const fields = (keys) => Object.keys(value).every((k) => keys.includes(k));
  const list = (v, valid) => Array.isArray(v) && v.length > 0 && v.length <= 32 && v.every(valid);
  if (value.kind === "forbidden-colors" && fields(["kind", "colors"]) && list(value.colors, color)) return value;
  if (value.kind === "forbidden-pair" && fields(["kind", "foreground", "background"]) && color(value.foreground) && color(value.background)) return value;
  if (value.kind === "filename" && fields(["kind", "extension", "style"]) && ["ts", "tsx", "js", "jsx", "css"].includes(String(value.extension)) && ["kebab-case", "camelCase", "PascalCase"].includes(String(value.style))) return value;
  if (value.kind === "formatter-config" && fields(["kind", "file", "required"]) && typeof value.file === "string" && /^(?:\.prettierrc(?:\.(?:json|ya?ml))?|\.eslintrc\.(?:json|ya?ml))$/u.test(value.file) && value.required && typeof value.required === "object" && !Array.isArray(value.required) && Object.keys(value.required).length > 0 && Object.keys(value.required).length <= 16 && Object.entries(value.required).every(([k, v]) => /^[A-Za-z][A-Za-z0-9_-]{0,63}$/u.test(k) && (typeof v === "boolean" || typeof v === "number" && Number.isFinite(v) || typeof v === "string" && v.length <= 120))) return value;
  const dependency = (v) => typeof v === "string" && /^(?:@[a-z0-9][a-z0-9._-]{0,63}\/)?[a-z0-9][a-z0-9._-]{0,63}$/u.test(v);
  if (value.kind === "dependencies" && fields(["kind", "section", "allow", "deny"]) && ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies"].includes(String(value.section)) && (value.allow !== void 0 || value.deny !== void 0) && (value.allow === void 0 || list(value.allow, dependency)) && (value.deny === void 0 || list(value.deny, dependency))) return value;
  return;
}
function conventionProblem(key, value) {
  if (!key.startsWith("validate.")) return null;
  return parseConventionRule(value) ? null : "A validate.* rule needs one of the checkable convention shapes (use a preset).";
}
var CONVENTION_PRESETS = [
  { id: "colors", en: "Forbidden color", ru: "\u0417\u0430\u043F\u0440\u0435\u0449\u0451\u043D\u043D\u044B\u0439 \u0446\u0432\u0435\u0442", key: "validate.colors", category: "design", value: { kind: "forbidden-colors", colors: ["#000000"] } },
  { id: "pair", en: "Forbidden color pair", ru: "\u041F\u0430\u0440\u0430 \u0446\u0432\u0435\u0442\u043E\u0432", key: "validate.pair", category: "design", value: { kind: "forbidden-pair", foreground: "#000000", background: "#ffffff" } },
  { id: "formatter", en: "Formatter settings", ru: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u0444\u043E\u0440\u043C\u0430\u0442\u0442\u0435\u0440\u0430", key: "validate.formatter", category: "code-style", value: { kind: "formatter-config", file: ".prettierrc.json", required: { semi: true } } },
  { id: "filenames", en: "File names", ru: "\u0418\u043C\u0435\u043D\u0430 \u0444\u0430\u0439\u043B\u043E\u0432", key: "validate.filenames", category: "naming", value: { kind: "filename", extension: "tsx", style: "PascalCase" } },
  { id: "dependencies", en: "Dependencies", ru: "\u0417\u0430\u0432\u0438\u0441\u0438\u043C\u043E\u0441\u0442\u0438", key: "validate.dependencies", category: "dependencies", value: { kind: "dependencies", section: "dependencies", deny: ["example-package"] } }
];
var TOKEN_PRESETS = [
  { id: "color", en: "Color", ru: "\u0426\u0432\u0435\u0442", key: "design.colors.name", category: "design", value: "#000000" },
  { id: "typography", en: "Typography", ru: "\u0422\u0438\u043F\u043E\u0433\u0440\u0430\u0444\u0438\u043A\u0430", key: "design.typography.name", category: "design", value: "16px/1.5 system-ui" },
  { id: "spacing", en: "Spacing", ru: "\u041E\u0442\u0441\u0442\u0443\u043F", key: "design.spacing.name", category: "design", value: "8px" },
  { id: "radius", en: "Radius", ru: "\u0420\u0430\u0434\u0438\u0443\u0441", key: "design.radius.name", category: "design", value: "6px" },
  { id: "component", en: "Component colors", ru: "\u0426\u0432\u0435\u0442\u0430 \u043A\u043E\u043C\u043F\u043E\u043D\u0435\u043D\u0442\u0430", key: "design.components.name", category: "design", value: { foreground: "#000000", background: "#ffffff" } }
];

// src/service/delivery.ts
var DELIVERY_CLIS = ["claude", "codex", "grok"];
var isDeliveryCli = (value) => DELIVERY_CLIS.includes(value);
var MAX_ARG = 1024;
var CORE_WORDS = /dangerously|approval_policy|approvals_reviewer|sandbox_mode|bypass|^hooks[.=]/iu;
var tomlString = (text) => JSON.stringify(text).replace(/\u007f/gu, "\\u007f");
var codexArg = (text) => `developer_instructions=${tomlString(text)}`;
var oneLine = (text) => text.replace(/\s+/gu, " ").trim();
var DELIVERY = {
  // --append-system-prompt-file: added to Claude Code's own system prompt, nothing replaced.
  claude: { how: "a file appended to the system prompt (--append-system-prompt-file)", budget: 24 * 1024, measure: bytes },
  // Codex developer instructions (-c developer_instructions=…), next to AGENTS.md, not instead of it.
  codex: { how: "developer instructions (-c developer_instructions=\u2026)", budget: MAX_ARG, measure: (text) => codexArg(text).length },
  grok: { how: "rules appended to the system prompt (--rules)", budget: MAX_ARG, measure: (text) => oneLine(text).length }
};
function contributionFor(cli, text) {
  const base = { env: {}, secretEnv: {}, args: [], files: [] };
  if (cli === "claude") {
    return { ...base, args: ["--append-system-prompt-file", "{launchFiles}/rules.md"], files: [{ relPath: "rules.md", content: text }] };
  }
  const arg = cli === "codex" ? codexArg(text) : oneLine(text);
  if (arg.length > MAX_ARG) throw new Error(`The rules are ${arg.length} characters as one argument; ${cli === "codex" ? "Codex" : "Grok"} takes at most ${MAX_ARG} at launch.`);
  const word = CORE_WORDS.exec(arg)?.[0];
  if (word) throw new Error(`A rule contains "${word}", which CanvasTTY never lets a plugin pass to ${cli === "codex" ? "Codex" : "Grok"} as an argument; reword it or turn off Send rules.`);
  return { ...base, args: cli === "codex" ? ["-c", arg] : ["--rules", arg] };
}

// src/service/importer.ts
import { createHash } from "node:crypto";
import { closeSync, constants, fstatSync, lstatSync, openSync, readdirSync, readSync, realpathSync } from "node:fs";
import { isAbsolute, join, relative, sep } from "node:path";
var MAX_FILE_BYTES = 64 * 1024;
var MAX_TOTAL_BYTES = 256 * 1024;
var hash = (value) => createHash("sha256").update(value).digest("hex");
var within = (root, path) => {
  const part = relative(root, path);
  return !isAbsolute(part) && part !== ".." && !part.startsWith(`..${sep}`);
};
function rootIdentity(path) {
  const s = lstatSync(path);
  if (!s.isDirectory() || realpathSync(path) !== path || process.getuid && s.uid !== process.getuid()) throw new Error("The project folder must be a real folder you own (not a link).");
  return `${s.dev}:${s.ino}:${s.uid}`;
}
function readSource(project, entry, projects) {
  if (rootIdentity(project.root) !== project.rootIdentity) throw new Error(`The folder of ${project.label} was replaced; add the project again.`);
  const target = join(project.root, entry.path);
  if (projects.some((p) => p.id !== project.id && p.root.length > project.root.length && within(project.root, p.root) && within(p.root, target))) throw new Error(`${entry.path} belongs to another registered project inside this one.`);
  const rootStat = lstatSync(project.root);
  try {
    let parent = project.root;
    for (const component of entry.path.split("/").slice(0, -1)) {
      parent = join(parent, component);
      const s = lstatSync(parent);
      if (!s.isDirectory() || s.isSymbolicLink() || s.dev !== rootStat.dev || s.uid !== rootStat.uid || realpathSync(parent) !== parent) throw new Error("unsafe folder");
    }
    const fd = openSync(target, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK);
    try {
      const before = fstatSync(fd);
      if (!before.isFile() || before.nlink !== 1 || before.dev !== rootStat.dev || before.uid !== rootStat.uid || before.size > MAX_FILE_BYTES) throw new Error("unsafe or too large file");
      const now = lstatSync(target);
      if (now.dev !== before.dev || now.ino !== before.ino || realpathSync(target) !== target) throw new Error("changed while opening");
      const data = Buffer.alloc(before.size + 1);
      let length = 0;
      while (length < data.length) {
        const count = readSync(fd, data, length, data.length - length, length);
        if (!count) break;
        length += count;
      }
      const after = fstatSync(fd);
      if (length !== before.size || before.mtimeMs !== after.mtimeMs || before.ctimeMs !== after.ctimeMs) throw new Error("changed while reading");
      const text = new TextDecoder("utf-8", { fatal: true }).decode(data.subarray(0, length));
      checkText(text, MAX_FILE_BYTES, "file text", true);
      return text;
    } finally {
      closeSync(fd);
    }
  } catch (error) {
    if (error.code === "ENOENT") return void 0;
    throw new Error(`${entry.path} could not be read safely (a plain UTF-8 file of yours up to 64 KB, not a link).`, { cause: error });
  }
}
function importProject(project, projects, room = MAX_RULES) {
  const rules = [], diagnostics = [];
  if (!project?.imports?.length) return { rules, diagnostics };
  checkImports(project.imports);
  let total = 0;
  for (const entry of project.imports) {
    const text = readSource(project, entry, projects);
    const diagnostic = (status, message) => {
      diagnostics.push({ sourcePath: entry.path, status, message });
    };
    if (text === void 0) {
      diagnostic("missing", "The file is gone; it adds no rules.");
      continue;
    }
    total += bytes(text);
    if (total > MAX_TOTAL_BYTES) throw new Error("The selected project files are larger than 256 KB together; select fewer.");
    const add = (key, value, sourceLine, category) => {
      if (rules.length >= room) throw new Error(`The imported files make more than ${MAX_RULES} rules; select fewer.`);
      const rule = {
        id: `import-${hash(`${project.id}:${entry.path}:${key}:${rules.length}`).slice(0, 48)}`,
        scope: "project",
        ownerId: project.id,
        category,
        key,
        value,
        enabled: true,
        source: "imported",
        updatedAt: rules.length,
        provenance: { sourcePath: entry.path, sourceLine }
      };
      checkRule(rule);
      rules.push(rule);
    };
    if (entry.kind === "css") {
      const parsed = cssTokens(text, entry.selectors ?? [":root"]);
      for (const token of parsed.tokens) add(`design.css.${token.selector === ":root" ? "" : `theme.${token.selector}.`}${token.name}`, token.value, token.line, "design");
      if (parsed.unsupported) diagnostic("unsupported", "Only literal custom properties in the selected top-level blocks are imported; nested, @media or computed CSS is not.");
    } else if (entry.kind === "config") {
      if (/\.(?:[cm]?js|ts)$/u.test(entry.path)) {
        diagnostic("reference", "JavaScript and TypeScript configs are never run, so nothing is imported from them.");
        continue;
      }
      let config;
      try {
        config = JSON.parse(text);
      } catch {
        diagnostic("reference", /\.ya?ml$/u.test(entry.path) || !text.trim().startsWith("{") ? "YAML configs are not imported; only JSON ones are." : "The file is not valid JSON.");
        continue;
      }
      if (!config || typeof config !== "object" || Array.isArray(config) || Object.keys(config).length > 64) throw new Error(`${entry.path} must be one JSON object of at most 64 settings.`);
      checkRule({ id: "config-check", scope: "user", category: "code-style", key: "config", value: config, enabled: true, source: "explicit", updatedAt: 0 });
      const tool = /prettier/u.test(entry.path) ? "prettier" : "eslint";
      for (const [key, value] of Object.entries(config)) {
        const at = text.indexOf(JSON.stringify(key));
        add(`code-style.${tool}.${key}`, value, at < 0 ? 1 : text.slice(0, at).split("\n").length, "code-style");
      }
    } else if (entry.kind === "editorconfig") {
      let section = "*";
      for (const [index, raw] of text.split("\n").entries()) {
        const line = raw.trim();
        if (!line || /^[#;]/u.test(line)) continue;
        if (/^\[[^\]\x00-\x1f]+\]$/u.test(line)) {
          section = line.slice(1, -1);
          continue;
        }
        const property = /^([A-Za-z_][A-Za-z0-9_-]*)\s*=\s*(.+)$/u.exec(line);
        if (!property) {
          diagnostic("unsupported", `Line ${index + 1} is not a plain "name = value".`);
          continue;
        }
        add(`code-style.editorconfig.${hash(section).slice(0, 12)}.${property[1]}`, { section, setting: property[1], value: property[2] }, index + 1, "code-style");
      }
    } else {
      let lines = text.split("\n").map((value, index2) => ({ value, line: index2 + 1 }));
      if (entry.path.endsWith(".mdc") && lines[0]?.value.trim() === "---") {
        const end = lines.findIndex((l, i) => i > 0 && l.value.trim() === "---");
        const front = end > 0 ? lines.slice(1, end).map((l) => l.value).join("\n") : "";
        if (!alwaysAppliedCursorFrontmatter(front)) {
          diagnostic("unsupported", "Only Cursor rules with alwaysApply: true (and an optional description) are imported; rules scoped by globs are not.");
          continue;
        }
        lines = lines.slice(end + 1);
      }
      if (entry.kind === "readme") lines = readmeSections(lines);
      const chunks = [];
      for (const line of lines) {
        let part = "", partBytes = 0;
        for (const c of line.value + "\n") {
          const size = bytes(c);
          if (partBytes + size > 1800) {
            chunks.push({ value: part, line: line.line });
            part = "";
            partBytes = 0;
          }
          part += c;
          partBytes += size;
        }
        if (part) {
          const last = chunks.at(-1);
          if (last && bytes(last.value + part) <= 1800) last.value += part;
          else chunks.push({ value: part, line: line.line });
        }
      }
      const name = entry.path.split("/").at(-1).replace(/^\.+/u, "").replace(/\.(md|mdc)$/iu, "").toLowerCase().replace(/[^a-z0-9-]+/gu, "-") || "file";
      let index = 0;
      for (const chunk of chunks) {
        if (chunk.value.trim()) add(`convention.${name}.${hash(entry.path).slice(0, 8)}.${++index}`, chunk.value.trim(), chunk.line, /CONTRIBUTING|README/iu.test(entry.path) ? "documentation" : "architecture");
      }
    }
  }
  return { rules, diagnostics };
}
function readmeSections(lines) {
  let selectedLevel = 0, fence = "";
  return lines.filter((l) => {
    const marker = /^ {0,3}(`{3,}|~{3,})/u.exec(l.value)?.[1];
    if (marker) {
      if (!fence) fence = marker;
      else if (marker[0] === fence[0] && marker.length >= fence.length && /^ {0,3}(?:`+|~+)\s*$/u.test(l.value)) fence = "";
      return !!selectedLevel;
    }
    if (fence) return !!selectedLevel;
    const heading = /^ {0,3}(#{1,6})\s+(.+)$/u.exec(l.value);
    if (heading) {
      if (selectedLevel && heading[1].length <= selectedLevel) selectedLevel = 0;
      if (/\b(develop(?:ment|er)?|contribut(?:ing|ion)|testing|code style)\b|разработ|тестирован|стиль кода/iu.test(heading[2])) selectedLevel = heading[1].length;
    }
    return !!selectedLevel;
  });
}
function alwaysAppliedCursorFrontmatter(front) {
  const keys = /* @__PURE__ */ new Set();
  for (const raw of front.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    const colon = line.indexOf(":");
    if (colon < 0) return false;
    const key = line.slice(0, colon);
    if (keys.has(key) || key !== "alwaysApply" && key !== "description") return false;
    if (key === "alwaysApply" && line.slice(colon + 1).trim() !== "true") return false;
    keys.add(key);
  }
  return keys.has("alwaysApply");
}
function cssTokens(text, selectors) {
  const tokens = [];
  let unsupported = false, clean = "", quote = "", comment = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (comment) {
      if (c === "*" && text[i + 1] === "/") {
        clean += "  ";
        i++;
        comment = false;
      } else clean += c === "\n" ? "\n" : " ";
      continue;
    }
    if (quote) {
      clean += c;
      if (c === "\\") {
        clean += text[++i] ?? "";
      } else if (c === quote) quote = "";
      continue;
    }
    if (c === "/" && text[i + 1] === "*") {
      clean += "  ";
      i++;
      comment = true;
    } else {
      clean += c;
      if (c === '"' || c === "'") quote = c;
    }
  }
  if (comment || quote) throw new Error("The CSS file has an unclosed comment or string.");
  let start = 0, bodyStart = 0, depth = 0, selector = "";
  quote = "";
  for (let i = 0; i < clean.length; i++) {
    const c = clean[i];
    if (quote) {
      if (c === "\\") i++;
      else if (c === quote) quote = "";
      continue;
    }
    if (c === '"' || c === "'") {
      quote = c;
      continue;
    }
    if (c === "{") {
      if (depth++ === 0) {
        selector = clean.slice(start, i).trim();
        bodyStart = i + 1;
      } else unsupported = true;
    } else if (c === "}") {
      if (--depth < 0) throw new Error("The CSS file has an unbalanced brace.");
      if (!depth) {
        const body = clean.slice(bodyStart, i);
        if (selectors.includes(selector) && !/[{}\\]/u.test(body)) {
          let declaration = 0, parentheses = 0;
          quote = "";
          for (let j = 0; j <= body.length; j++) {
            const char = body[j];
            if (quote) {
              if (char === quote) quote = "";
              continue;
            }
            if (char === '"' || char === "'") {
              quote = char;
              continue;
            }
            if (char === "(") parentheses++;
            if (char === ")") parentheses--;
            if (j === body.length || char === ";" && !parentheses) {
              const part = body.slice(declaration, j), match = /^\s*(--[A-Za-z_][A-Za-z0-9_-]*)\s*:\s*([\s\S]+?)\s*$/u.exec(part);
              if (match) tokens.push({ name: match[1], value: match[2], selector, line: clean.slice(0, bodyStart + declaration + part.indexOf(match[1])).split("\n").length });
              else if (part.includes("--")) unsupported = true;
              declaration = j + 1;
            }
          }
          if (parentheses || quote) throw new Error("The CSS file has an unbalanced declaration.");
        } else if (selector.startsWith("@") || selectors.includes(selector)) unsupported = true;
        start = i + 1;
      }
    } else if (c === ";" && !depth) start = i + 1;
  }
  if (depth) throw new Error("The CSS file has an unbalanced brace.");
  return { tokens, unsupported };
}
var FIXED = [
  { path: "AGENTS.md", kind: "instructions" },
  { path: "CLAUDE.md", kind: "instructions" },
  { path: "GEMINI.md", kind: "instructions" },
  { path: "CONTRIBUTING.md", kind: "instructions" },
  { path: ".cursorrules", kind: "instructions" },
  { path: ".windsurfrules", kind: "instructions" },
  { path: ".github/copilot-instructions.md", kind: "instructions" },
  { path: "README.md", kind: "readme" },
  { path: ".editorconfig", kind: "editorconfig" },
  { path: ".prettierrc", kind: "config" },
  { path: ".prettierrc.json", kind: "config" },
  { path: ".prettierrc.yaml", kind: "config" },
  { path: ".prettierrc.yml", kind: "config" },
  { path: ".eslintrc", kind: "config" },
  { path: ".eslintrc.json", kind: "config" }
];
function discover(project) {
  if (rootIdentity(project.root) !== project.rootIdentity) throw new Error(`The folder of ${project.label} was replaced; add the project again.`);
  const selected = new Set((project.imports ?? []).map((entry) => entry.path));
  const found = [];
  const isFile = (path) => {
    try {
      const s = lstatSync(join(project.root, path));
      return s.isFile() && s.size <= MAX_FILE_BYTES;
    } catch {
      return false;
    }
  };
  const list = (folder) => {
    try {
      return readdirSync(join(project.root, folder)).sort().slice(0, 200);
    } catch {
      return [];
    }
  };
  for (const entry of FIXED) if (isFile(entry.path)) found.push(entry);
  for (const name of list(".cursor/rules")) if (name.endsWith(".mdc") && isFile(`.cursor/rules/${name}`)) found.push({ path: `.cursor/rules/${name}`, kind: "instructions" });
  for (const folder of ["", "src", "styles", "src/styles", "app"]) {
    for (const name of list(folder).filter((name2) => name2.endsWith(".css")).slice(0, 8)) {
      const path = folder ? `${folder}/${name}` : name;
      if (isFile(path)) found.push({ path, kind: "css" });
    }
  }
  const candidates = found.filter((entry) => importNameSupported(entry.kind, entry.path)).slice(0, 48).map((entry) => ({ ...entry, selected: selected.has(entry.path) }));
  for (const entry of project.imports ?? []) if (!candidates.some((c) => c.path === entry.path)) candidates.push({ path: entry.path, kind: entry.kind, selected: true });
  return candidates;
}

// src/service/store.ts
import { randomUUID } from "node:crypto";
import { closeSync as closeSync2, constants as constants2, fstatSync as fstatSync2, openSync as openSync2, readFileSync, realpathSync as realpathSync2 } from "node:fs";
import { chmod, lstat, mkdir, open, rename, rm, stat } from "node:fs/promises";
import { isAbsolute as isAbsolute2, join as join2 } from "node:path";
var MAX_BYTES = 8 * 1024 * 1024;
var LOCK_WAIT_MS = 3e3;
var LOCK_STALE_MS = 3e4;
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
var RulesStore = class {
  folder;
  value;
  writes = Promise.resolve();
  constructor(dataDir) {
    this.folder = join2(dataDir, "rules");
  }
  get() {
    if (!this.value) {
      let raw;
      let fd;
      try {
        fd = openSync2(join2(this.folder, "rules.json"), constants2.O_RDONLY | constants2.O_NOFOLLOW | constants2.O_NONBLOCK);
        const info = fstatSync2(fd);
        if (!info.isFile() || info.size > MAX_BYTES || info.mode & 63) throw new Error("The rules file is not a private file of at most 8 MB.");
        raw = readFileSync(fd, "utf8");
      } catch (error) {
        const code = error.code;
        if (code === "ELOOP") throw new Error("The rules file is not a private file of at most 8 MB.");
        if (code !== "ENOENT") throw error;
      } finally {
        if (fd !== void 0) closeSync2(fd);
      }
      const value = raw === void 0 ? emptyState() : JSON.parse(raw);
      checkState(value);
      this.value = value;
    }
    return structuredClone(this.value);
  }
  /** The registered project whose folder holds `cwd` (the innermost one). */
  projectFor(cwd) {
    let path;
    try {
      path = realpathSync2(cwd);
    } catch {
      return void 0;
    }
    return this.get().projects.filter((p) => within(p.root, path)).sort((a, b) => b.root.length - a.root.length)[0];
  }
  /** The store's folder, created private; a link or someone else's folder in its place is refused. */
  async ensureFolder() {
    await mkdir(this.folder, { recursive: true, mode: 448 });
    const info = await lstat(this.folder);
    if (!info.isDirectory() || process.getuid && info.uid !== process.getuid()) throw new Error("The rules folder is not a private folder of yours.");
    if (info.mode & 63) await chmod(this.folder, 448);
  }
  /** Holds rules.lock (created exclusively) while `run` checks and replaces the file. */
  async locked(run) {
    const lock = join2(this.folder, "rules.lock");
    const deadline = Date.now() + LOCK_WAIT_MS;
    for (; ; ) {
      try {
        await (await open(lock, "wx", 384)).close();
        break;
      } catch (error) {
        if (error.code !== "EEXIST") throw error;
        const held = await stat(lock).catch(() => null);
        if (held && Date.now() - held.mtimeMs > LOCK_STALE_MS) {
          await rm(lock, { force: true });
          continue;
        }
        if (Date.now() > deadline) throw new Error("The rules are being saved elsewhere; try again.");
        await sleep(25);
      }
    }
    try {
      return await run();
    } finally {
      await rm(lock, { force: true });
    }
  }
  update(revision, change) {
    const operation = this.writes.catch(() => void 0).then(async () => {
      await this.ensureFolder();
      return this.locked(async () => {
        this.value = void 0;
        const next = this.get();
        if (!Number.isSafeInteger(revision) || revision !== next.revision) throw new Error("The rules changed meanwhile; reload and try again.");
        change(next);
        next.revision++;
        checkState(next);
        const raw = JSON.stringify(next);
        const temporary = join2(this.folder, `${randomUUID()}.tmp`);
        const file = await open(temporary, "wx", 384);
        try {
          await file.writeFile(raw);
          await file.sync();
        } finally {
          await file.close();
        }
        try {
          await rename(temporary, join2(this.folder, "rules.json"));
        } catch (error) {
          await rm(temporary, { force: true });
          throw error;
        }
        this.value = next;
        return structuredClone(next);
      });
    });
    this.writes = operation;
    return operation;
  }
  saveProject(input, revision) {
    return this.update(revision, (state) => {
      if (!input || Object.keys(input).some((key) => !["id", "label", "root", "organizationId"].includes(key))) throw new Error("Invalid project fields.");
      checkText(input.label, 160, "project name");
      checkText(input.root, 4096, "project folder");
      if (!isAbsolute2(input.root)) throw new Error("Give the project folder as a full path, for example /Users/you/project.");
      let root;
      try {
        root = realpathSync2(input.root);
      } catch {
        throw new Error("There is no such folder.");
      }
      const identity = rootIdentity(root);
      const organizationId = input.organizationId?.trim() || void 0;
      if (organizationId !== void 0) checkId(organizationId, "organization");
      const previous = input.id === void 0 ? void 0 : state.projects.find((p) => p.id === input.id);
      if (input.id !== void 0 && !previous) throw new Error("Unknown project.");
      if (state.projects.some((p) => p.root === root && p.id !== input.id)) throw new Error("This folder is already a project.");
      const project = {
        id: previous?.id ?? randomUUID(),
        label: input.label.trim(),
        root,
        rootIdentity: identity,
        ...organizationId ? { organizationId } : {},
        ...previous?.root === root && previous.imports ? { imports: previous.imports } : {}
      };
      state.projects = [...state.projects.filter((p) => p.id !== project.id), project];
      state.rules = state.rules.filter((r) => r.scope !== "organization" || state.projects.some((p) => p.organizationId === r.ownerId));
    });
  }
  saveImports(projectId, imports, revision) {
    return this.update(revision, (state) => {
      checkId(projectId, "project id");
      checkImports(imports);
      const project = state.projects.find((p) => p.id === projectId);
      if (!project) throw new Error("Unknown project.");
      if (rootIdentity(project.root) !== project.rootIdentity) throw new Error(`The folder of ${project.label} was replaced; add the project again.`);
      project.imports = imports.map((entry) => ({ path: entry.path, kind: entry.kind, ...entry.selectors ? { selectors: [...entry.selectors] } : {} }));
    });
  }
  saveTask(input, revision) {
    return this.update(revision, (state) => {
      if (!input || Object.keys(input).some((key) => !["id", "label", "projectId"].includes(key))) throw new Error("Invalid task fields.");
      checkText(input.label, 160, "task name");
      checkId(input.projectId, "project id");
      if (!state.projects.some((p) => p.id === input.projectId) || input.id !== void 0 && !state.tasks.some((t) => t.id === input.id && t.projectId === input.projectId)) throw new Error("Unknown task or project.");
      const task = { id: input.id ?? randomUUID(), label: input.label.trim(), projectId: input.projectId };
      state.tasks = [...state.tasks.filter((t) => t.id !== task.id), task];
    });
  }
  saveRule(input, revision) {
    return this.update(revision, (state) => {
      if (!input || typeof input !== "object" || Object.keys(input).some((key) => !["id", "scope", "ownerId", "category", "key", "value", "enabled"].includes(key))) throw new Error("Invalid rule fields.");
      if (input.id !== void 0 && !state.rules.some((r) => r.id === input.id)) throw new Error("Unknown rule (imported rules are read-only; override them instead).");
      const rule = {
        id: input.id ?? randomUUID(),
        scope: input.scope,
        ...input.ownerId ? { ownerId: input.ownerId } : {},
        category: input.category,
        key: typeof input.key === "string" ? input.key.trim() : input.key,
        value: structuredClone(input.value),
        enabled: input.enabled,
        source: "explicit",
        updatedAt: Date.now()
      };
      if (rule.scope === "current") throw new Error("A launch instruction is given in the launcher, not saved.");
      checkKey(rule.key);
      checkRule(rule);
      const problem = conventionProblem(rule.key, rule.value);
      if (problem) throw new Error(problem);
      state.rules = [...state.rules.filter((r) => r.id !== rule.id), rule];
    });
  }
  remove(kind, id, revision) {
    return this.update(revision, (state) => {
      checkId(id);
      if (kind === "rule") state.rules = state.rules.filter((r) => r.id !== id);
      else if (kind === "task") {
        state.tasks = state.tasks.filter((t) => t.id !== id);
        state.rules = state.rules.filter((r) => r.scope !== "task" || r.ownerId !== id);
      } else if (kind === "project") {
        state.projects = state.projects.filter((p) => p.id !== id);
        state.tasks = state.tasks.filter((t) => t.projectId !== id);
        state.rules = state.rules.filter((r) => r.scope === "project" ? r.ownerId !== id : r.scope === "task" ? state.tasks.some((t) => t.id === r.ownerId) : r.scope === "organization" ? state.projects.some((p) => p.organizationId === r.ownerId) : true);
      } else throw new Error("Invalid kind.");
    });
  }
};

// src/service/context.ts
var errorText = (error) => error instanceof Error ? error.message : String(error);
var refuse = (reason) => ({ refuse: { reason: reason.replace(/[\u0000-\u001f\u007f]+/gu, " ").slice(0, 240) } });
var NONE = "none";
var KEEPS_LAUNCH = /* @__PURE__ */ new Set(["canvastty-environments/worktree"]);
function notDeliveredBadge(kind) {
  const where = kind === "ssh-host" ? "server" : /container/u.test(kind) ? "container" : "environment";
  return {
    text: "Rules not delivered",
    tone: "warn",
    tooltip: `Project rules are not delivered on this ${where}: it does not pass the launch's files and arguments on. Give the agent the text of rules_for in its prompt if it needs them.`
  };
}
var ContextService = class {
  store;
  pluginId;
  host;
  constructor(options) {
    this.store = new RulesStore(options.dataDir);
    this.host = options.host;
    this.pluginId = options.pluginId ?? "canvastty-context";
  }
  /** The rules that apply to a folder (or a registered project), read now, sized for one agent CLI. */
  resolve(want) {
    const state = this.store.get();
    const project = want.projectId ? state.projects.find((p) => p.id === want.projectId) : want.cwd ? this.store.projectFor(want.cwd) : void 0;
    if (want.projectId && !project) throw new Error("Unknown project.");
    let task = null;
    if (want.taskId && want.taskId !== NONE) {
      task = state.tasks.find((t) => t.id === want.taskId) ?? null;
      if (!task) throw new Error("The saved task chosen for this launch no longer exists; choose another one.");
      if (task.projectId !== project?.id) throw new Error(`The task "${task.label.slice(0, 60)}" belongs to another project than this folder.`);
    }
    const category = want.category && want.category !== "all" ? want.category : void 0;
    if (category && !CATEGORIES.includes(category)) throw new Error(`Unknown category ${category.slice(0, 40)}.`);
    const imported = importProject(project, state.projects, MAX_RULES - state.rules.length);
    const current = [];
    if (want.current?.trim()) {
      checkText(want.current, 4096, "launch instruction");
      current.push({ id: "current", scope: "current", category: "communication", key: "launch.instruction", value: want.current.trim(), enabled: true, source: "explicit", updatedAt: Date.now() });
    }
    const delivery = DELIVERY[want.cli];
    const resolved = resolveRules([...state.rules, ...imported.rules, ...current], {
      ...project ? { projectId: project.id } : {},
      ...project?.organizationId ? { organizationId: project.organizationId } : {},
      ...task ? { taskId: task.id } : {},
      ...category ? { categories: [category] } : {},
      budget: delivery.budget,
      measure: delivery.measure
    });
    return { project: project ?? null, task, ...resolved, budget: delivery.budget, diagnostics: imported.diagnostics };
  }
  // ---- the settings page ----
  state() {
    return { state: this.store.get(), categories: CATEGORIES, presets: { conventions: CONVENTION_PRESETS, tokens: TOKEN_PRESETS } };
  }
  /** A project's imported rules and file notes, read now (the page shows them read-only). */
  imported(projectId) {
    const state = this.store.get();
    const project = state.projects.find((p) => p.id === projectId);
    if (!project) throw new Error("Unknown project.");
    try {
      return importProject(project, state.projects, MAX_RULES - state.rules.length);
    } catch (error) {
      return { error: errorText(error) };
    }
  }
  discover(projectId) {
    const project = this.store.get().projects.find((p) => p.id === projectId);
    if (!project) throw new Error("Unknown project.");
    return discover(project);
  }
  preview(params) {
    const cli = isDeliveryCli(params.provider) ? params.provider : "claude";
    const result = this.resolve({
      cli,
      ...typeof params.projectId === "string" && params.projectId ? { projectId: params.projectId } : {},
      ...typeof params.taskId === "string" ? { taskId: params.taskId } : {},
      ...typeof params.category === "string" ? { category: params.category } : {}
    });
    return { ...result, included: result.included.map((rule) => ({ scope: rule.scope, category: rule.category, key: rule.key, source: rule.source })) };
  }
  saveProject(params) {
    return this.store.saveProject(params.project, Number(params.revision));
  }
  saveImports(params) {
    return this.store.saveImports(String(params.projectId), params.imports, Number(params.revision));
  }
  saveTask(params) {
    return this.store.saveTask(params.task, Number(params.revision));
  }
  saveRule(params) {
    return this.store.saveRule(params.rule, Number(params.revision));
  }
  remove(params) {
    return this.store.remove(params.kind, String(params.id), Number(params.revision));
  }
  // ---- CanvasTTY: the launcher list and the launch ----
  /** `canvastty.launch.options`: the saved tasks, named with their project (the launcher does not say the folder yet). */
  launchOptions() {
    const state = this.store.get();
    const label = (task) => `${state.projects.find((p) => p.id === task.projectId)?.label ?? "?"} \xB7 ${task.label}`.slice(0, 120);
    return { task: state.tasks.slice(0, 64).map((task) => ({ value: task.id, label: label(task) })) };
  }
  /** `canvastty.launch.prepare`: "Send rules" on → the rules for the card's folder, delivered the CLI's way. */
  prepare(context) {
    if (context.chosen === false) return null;
    const options = context.options ?? {};
    if (options.send === false) return null;
    if (!isDeliveryCli(context.provider)) return refuse(`${context.provider} cannot receive rules at launch; turn off Send rules for it.`);
    if (context.environment && !KEEPS_LAUNCH.has(`${context.environment.pluginId}/${context.environment.kind}`)) {
      void this.host?.callHost("cards.setBadge", { sessionId: context.sessionId, badge: notDeliveredBadge(context.environment.kind) }).catch(() => void 0);
      return null;
    }
    try {
      const result = this.resolve({
        cli: context.provider,
        cwd: context.cwd,
        ...typeof options.task === "string" ? { taskId: options.task } : {},
        ...typeof options.category === "string" ? { category: options.category } : {},
        ...typeof options.current === "string" ? { current: options.current } : {}
      });
      if (!result.text) return null;
      return contributionFor(context.provider, result.text);
    } catch (error) {
      return refuse(errorText(error));
    }
  }
  // ---- orchestrator tool ----
  tool(name, input, caller) {
    if (name !== "rules_for") return { content: `Unknown tool ${name.slice(0, 40)}.`, isError: true };
    const text = (value, max) => typeof value === "string" && value.trim() ? value.trim().slice(0, max) : void 0;
    const folder = text(input.folder, 4096) ?? caller?.cwd;
    if (!folder || !folder.startsWith("/")) return { content: "Give `folder` as a full path (or call from a card that has a folder).", isError: true };
    const provider = text(input.provider, 20) ?? "claude";
    if (!isDeliveryCli(provider)) return { content: "Rules reach claude, codex and grok at launch; give one of them as `provider`, or leave it out.", isError: true };
    const state = this.store.get();
    const project = this.store.projectFor(folder);
    const taskName = text(input.task, 160);
    let taskId;
    if (taskName) {
      const task = state.tasks.find((t) => t.projectId === project?.id && (t.id === taskName || t.label.toLowerCase() === taskName.toLowerCase()));
      if (!task) {
        const known = state.tasks.filter((t) => t.projectId === project?.id).map((t) => t.label);
        return { content: `No saved task "${taskName}" in ${project ? `project ${project.label}` : "this folder (it is in no registered project)"}.${known.length ? ` Tasks: ${known.join(", ")}.` : ""}`, isError: true };
      }
      taskId = task.id;
    }
    const category = text(input.category, 40);
    try {
      const result = this.resolve({ cli: provider, cwd: folder, ...taskId ? { taskId } : {}, ...category ? { category } : {} });
      return { content: {
        folder,
        project: result.project ? { name: result.project.label, folder: result.project.root, organization: result.project.organizationId ?? null } : null,
        task: result.task?.label ?? null,
        rules: result.included.map((rule) => ({ scope: rule.scope, category: rule.category, key: rule.key, value: rule.value, source: rule.source })),
        omitted: result.omitted,
        text: result.text,
        notes: result.diagnostics.map((d) => `${d.sourcePath}: ${d.message}`),
        launchOptions: { [this.pluginId]: { send: true, task: taskId ?? NONE, category: category ?? "all", current: "" } },
        howTo: `Rules apply in this order: the launch's own instruction, task, project, organization, user, defaults. To give a subagent these rules at launch, pass launchOptions to spawn_agent unchanged (provider claude, codex or grok; ${provider} gets them as ${DELIVERY[provider].how}). They reach an agent on this computer or in a worktree; on a server or in a container the agent starts without them, so put the text in the prompt instead.`
      } };
    } catch (error) {
      return { content: errorText(error), isError: true };
    }
  }
};

// src/service/main.ts
var resolveReady;
var ready = new Promise((resolve) => {
  resolveReady = resolve;
});
serve({
  onInitialize: (params, host) => {
    const dataDir = typeof params.dataDir === "string" ? params.dataDir : process.cwd();
    resolveReady(new ContextService({ host, dataDir, ...typeof params.pluginId === "string" ? { pluginId: params.pluginId } : {} }));
  },
  methods: {
    // Host-only requests.
    "canvastty.launch.options": async () => (await ready).launchOptions(),
    "canvastty.launch.prepare": async (params) => (await ready).prepare(params),
    "canvastty.tools.call": async (params) => (await ready).tool(String(params.tool), params.input ?? {}, params.caller),
    // The settings page.
    state: async () => (await ready).state(),
    imported: async (params) => (await ready).imported(params.projectId),
    discover: async (params) => (await ready).discover(params.projectId),
    preview: async (params) => (await ready).preview(params),
    saveProject: async (params) => (await ready).saveProject(params),
    saveImports: async (params) => (await ready).saveImports(params),
    saveTask: async (params) => (await ready).saveTask(params),
    saveRule: async (params) => (await ready).saveRule(params),
    remove: async (params) => (await ready).remove(params)
  }
});
