// Builds the installable package in place: CanvasTTY's installer runs no build and no npm install, so the service is
// one bundled file (services/context.mjs), the settings page script is one file (settings/context.js), and the
// manifest's coreFiles carry the exact bytes and SHA-256 of every file it installs.
//   ESBUILD=/path/to/esbuild node scripts/build.mjs   (default: node_modules/.bin/esbuild)
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const esbuild = process.env.ESBUILD || join(root, "node_modules/.bin/esbuild");
if (!existsSync(esbuild)) throw new Error(`esbuild not found at ${esbuild}; run npm install or set ESBUILD.`);

const banner = "// Generated by scripts/build.mjs from src/; edit the sources, not this file.";
execFileSync(esbuild, ["src/service/main.ts", "--bundle", "--platform=node", "--format=esm", "--target=node20",
  "--outfile=services/context.mjs", `--banner:js=${banner}`, "--log-level=warning"], { cwd: root, stdio: "inherit" });
execFileSync(esbuild, ["src/ui/settings.ts", "--bundle", "--platform=browser", "--format=iife", "--target=es2022",
  "--outfile=settings/context.js", `--banner:js=${banner}`, "--log-level=warning"], { cwd: root, stdio: "inherit" });

const manifestPath = join(root, "canvastty.plugin.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const stamp = (file) => {
  const bytes = readFileSync(join(root, file.path));
  return { path: file.path, bytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex") };
};
manifest.coreFiles = manifest.coreFiles.map(stamp);
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
console.log("built services/context.mjs, settings/context.js and stamped canvastty.plugin.json");
